'use client';
import {CSSProperties,ReactNode,useEffect,useRef,useState,PointerEvent,KeyboardEvent} from 'react';
type Sizes={left:number;right:number;bottom:number};
const defaults:Sizes={left:232,right:272,bottom:206};
const ranges={left:[180,360],right:[220,400],bottom:[130,360]} as const;
export default function EditorFrame({scene,inspector,viewport,console:bottom,tab,setTab,hasResult}:{scene:ReactNode;inspector:ReactNode;viewport:ReactNode;console:ReactNode;tab:string;setTab:(tab:string)=>void;hasResult:boolean}){
 const [sizes,setSizes]=useState(defaults),[ready,setReady]=useState(false),[visible,setVisible]=useState({left:true,right:true,bottom:true});const root=useRef<HTMLDivElement>(null);
 const drag=useRef<{axis:keyof Sizes;start:number;size:number}|null>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('worldforge.editor.v1')??'null');if(saved){const result={...defaults};for(const axis of ['left','right','bottom'] as const){if(Number.isFinite(saved[axis]))result[axis]=Math.max(ranges[axis][0],Math.min(ranges[axis][1],saved[axis]));}setSizes(result);}}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('worldforge.editor.v1',JSON.stringify(sizes));}catch{}},[sizes,ready]);
 useEffect(()=>{if(hasResult)setVisible(v=>({...v,bottom:true}));},[hasResult]);
 function adjust(axis:keyof Sizes,value:number){const area=root.current;let maximum:number=ranges[axis][1];if(area){if(axis==='bottom')maximum=Math.min(maximum,area.clientHeight-310);else maximum=Math.min(maximum,area.clientWidth-380-(axis==='left'?(visible.right?sizes.right:0):(visible.left?sizes.left:0)));}setSizes(s=>({...s,[axis]:Math.max(ranges[axis][0],Math.min(Math.max(ranges[axis][0],maximum),value))}));}
 function start(axis:keyof Sizes,e:PointerEvent<HTMLDivElement>){e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={axis,start:axis==='bottom'?e.clientY:e.clientX,size:sizes[axis]};}
 function move(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(d){const position=d.axis==='bottom'?e.clientY:e.clientX;adjust(d.axis,d.size+(position-d.start)*(d.axis==='left'?1:-1));}}
 function key(axis:keyof Sizes,e:KeyboardEvent<HTMLDivElement>){if(e.key==='Home'){adjust(axis,defaults[axis]);e.preventDefault();return;}const delta=(e.key==='ArrowRight'||e.key==='ArrowDown')?16:(e.key==='ArrowLeft'||e.key==='ArrowUp')?-16:0;if(delta){e.preventDefault();adjust(axis,sizes[axis]+delta*(axis==='left'?1:-1));}}
 function divider(axis:keyof Sizes){return <div className={'panel-divider divider-'+axis} role="separator" aria-label={'Resize '+(axis==='left'?'scene':axis==='right'?'inspector':'console')+' panel'} aria-orientation={axis==='bottom'?'horizontal':'vertical'} aria-valuemin={ranges[axis][0]} aria-valuemax={ranges[axis][1]} aria-valuenow={sizes[axis]} tabIndex={0} onKeyDown={e=>key(axis,e)} onPointerDown={e=>start(axis,e)} onPointerMove={move} onPointerUp={e=>{drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);}} onLostPointerCapture={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onDoubleClick={()=>adjust(axis,defaults[axis])}/>;}
 return <><nav className="workspace-tools" aria-label="Workspace panels"><div>{(['left','right','bottom'] as const).map((axis,i)=><button key={axis} aria-pressed={visible[axis]} onClick={()=>setVisible(v=>({...v,[axis]:!v[axis]}))}>{['Scene','Inspector','Console'][i]}</button>)}</div><button title="Restore panel sizes and visibility" onClick={()=>{setSizes(defaults);setVisible({left:true,right:true,bottom:true});}}>Reset layout</button></nav>
 <div ref={root} className={'editor-frame'+(!visible.left?' hide-scene':'')+(!visible.right?' hide-inspector':'')+(!visible.bottom?' hide-console':'')} style={{'--left-size':sizes.left+'px','--right-size':sizes.right+'px','--bottom-size':sizes.bottom+'px'} as CSSProperties}>
 <aside className="scene-panel editor-panel" aria-label="Scene hierarchy"><div className="panel-caption">Scene</div><div className="panel-scroll">{scene}</div></aside>{divider('left')}
 <section className="editor-viewport">{viewport}</section>{divider('right')}
 <aside className="inspector-panel editor-panel" aria-label="Inspector"><div className="panel-caption">Inspector</div><div className="panel-scroll">{inspector}</div></aside>{divider('bottom')}
 <section className="console-panel editor-panel" aria-label="Chat and results"><div className="console-tabs" role="tablist" aria-label="Console" onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=tab==='chat'?'results':'chat';setTab(next);document.getElementById(next+'-tab')?.focus();}}}><button id="chat-tab" role="tab" tabIndex={tab==='chat'?0:-1} aria-selected={tab==='chat'} aria-controls="console-content" onClick={()=>setTab('chat')}>Chat</button><button id="results-tab" role="tab" tabIndex={tab==='results'?0:-1} aria-selected={tab==='results'} aria-controls="console-content" onClick={()=>setTab('results')}>Results{hasResult&&<span className="result-dot"/>}</button><button className="console-collapse" aria-label="Collapse console" onClick={()=>setVisible(v=>({...v,bottom:false}))}>⌄</button></div><div id="console-content" role="tabpanel" aria-labelledby={tab==='chat'?'chat-tab':'results-tab'} className="console-content">{bottom}</div></section>
 </div></>;
}
